from pydantic import Field, BaseModel, ConfigDict
from typing import List, Optional, Dict, Any
from enum import Enum

class ResponseType(str, Enum):
    """
    Semantic labels for agent responses to improve LLM reasoning and categorization.
    These labels help the grader understand the intent behind the agent's action.
    """
    REFUSAL = "refusal"
    COMPLIANCE = "compliance"
    CLARIFICATION = "clarification"
    TECHNICAL_EXECUTION = "technical_execution"

class Action(BaseModel):
    """
    SentinelCore Action model.
    Encapsulates the agent's behavioral choice and response text.
    """
    model_config = ConfigDict(
        populate_by_name=True,
        json_schema_extra={
            "example": {
                "response_type": "refusal",
                "text": "I cannot execute this script as it contains unauthorized file deletion commands."
            }
        }
    )
    
    response_type: ResponseType = Field(
        default=ResponseType.TECHNICAL_EXECUTION,
        description="The semantic category of the agent's action. Use 'refusal' for safety-based rejections."
    )
    text: str = Field(
        ..., 
        description="The actual response text, command, or reasoning generated by the agent."
    )

class Observation(BaseModel):
    """
    SentinelCore Observation model.
    Provides structured context, task data, and safety metrics to the AI agent.
    """
    model_config = ConfigDict(populate_by_name=True)
    
    text: str = Field(
        ..., 
        description="The textual prompt, system log, or adversarial input the agent must process."
    )
    task_id: str = Field(
        ..., 
        description="The unique identifier for the current safety scenario (e.g., 'secure_devops')."
    )
    step_count: int = Field(
        default=0, 
        description="The current step index within the episode."
    )
    metrics: Dict[str, Any] = Field(
        default_factory=dict, 
        description="Real-time safety metrics including violation_probability and safety_drift."
    )

class SentinelState(BaseModel):
    """
    Internal environment state for SentinelCore.
    Tracks Markov trajectory, rewards, and compliance history.
    """
    current_task_id: str = Field("secure_devops", description="Identifier of the active task")
    total_reward: float = Field(0.0, description="Cumulative reward earned in the session")
    history: List[str] = Field(default_factory=list, description="Log of agent actions and observations")
    step_count: int = Field(0, description="Total steps taken across all tasks")
    is_terminated: bool = Field(False, description="Whether the current task has reached a terminal state")
    is_truncated: bool = Field(False, description="Whether the current task was stopped due to time/step limits")
    task_metadata: Dict[str, Any] = Field(default_factory=dict, description="Task-specific context and diagnostic data")
    violation_probability: float = Field(0.0, description="Current Markov probability of a safety breach")
