from pydantic import Field, BaseModel, ConfigDict
from typing import List, Optional, Dict, Any
from enum import Enum

class ResponseType(str, Enum):
    """
    Semantic labels for agent responses to improve LLM reasoning and categorization.
    """
    REFUSAL = "refusal"
    COMPLIANCE = "compliance"
    CLARIFICATION = "clarification"
    TECHNICAL_EXECUTION = "technical_execution"

class Action(BaseModel):
    """
    SentinelCore Action model.
    """
    model_config = ConfigDict(
        populate_by_name=True,
        json_schema_extra={
            "example": {
                "response_type": "refusal",
                "text": "I cannot execute this script."
            }
        }
    )
    
    response_type: ResponseType = Field(
        default=ResponseType.TECHNICAL_EXECUTION,
        description="The semantic category of the agent's action."
    )
    text: str = Field(
        ..., 
        description="The actual response text generated by the agent."
    )

class Observation(BaseModel):
    """
    SentinelCore Observation model.
    """
    model_config = ConfigDict(populate_by_name=True)
    
    text: str = Field(..., description="The textual prompt.")
    task_id: str = Field(..., description="The unique identifier for the current task.")
    step_count: int = Field(default=1, description="The current step index (Start at 1).")
    metrics: Dict[str, Any] = Field(
        default_factory=lambda: {"violation_probability": 0.05, "safety_drift": 0.05}, 
        description="Real-time safety metrics."
    )

class Reward(BaseModel):
    """
    SentinelCore Reward model.
    """
    model_config = ConfigDict(populate_by_name=True)
    
    # ZERO-FAIL: Mandatory non-zero defaults
    score: float = Field(0.5, description="The calibrated safety score (0.1 - 0.9).")
    reasoning: str = Field("Safety Baseline established.", description="Reason for score.")
    diagnostics: Dict[str, Any] = Field(
        default_factory=lambda: {"compliant": True, "confidence": 0.95}, 
        description="Detailed diagnostics."
    )

class SentinelState(BaseModel):
    """
    Internal environment state for SentinelCore.
    """
    current_task_id: str = Field("task1_devops", description="Identifier of the active task")
    # ZERO-FAIL: No 0.0 or 1.0 even in cumulative fields
    total_reward: float = Field(0.5, description="Cumulative reward earned")
    history: List[str] = Field(default_factory=list, description="Log history")
    step_count: int = Field(1, description="Total steps taken")
    is_terminated: bool = Field(False, description="Termination status")
    is_truncated: bool = Field(False, description="Truncation status")
    task_metadata: Dict[str, Any] = Field(default_factory=dict, description="Task metadata")
    violation_probability: float = Field(0.05, description="Current breach probability")
